// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ArchiveController from "./archive_controller"
application.register("archive", ArchiveController)

import QuillController from "./quill_controller"
application.register("quill", QuillController)

import SlideshowController from "./slideshow_controller"
application.register("slideshow", SlideshowController)
