class PhotosController < ApplicationController
  def index
    @photos = %w[
      2017-HADLEY-JTREE-STEMGEM-SUNSET.jpg
      2018-HADLEY-AGUJA-POLLONE.jpg
      2015-HADLEY-GOTHIC-BASIN-CAMP.jpg
      2015-HADLEY-ENCHANTMENTS-TENT-AND-LARCHES.jpg
      2016-HADLEY-DENALI-2.jpg
      2016-HADLEY-STUART-REESE-ISLANDS-IN-SKY.jpg
      2016-HADLEY-BLAKE-SUMMIT-LIBERTY-CRACK.jpg
      2018-HADLEY-FITZ-AND-POINCENOT-SUNRISE.jpg
      2017-HADLEY-GUNSIGHT-RANGE.jpg
      2017-HADLEY-CHAIR-DESCENT.jpg
      2015-HADLEY-PRUSIK-PEAK-APPROACH.jpg
      2015-HADLEY-PRUSIK-LARCHES.jpeg
      2016-HADLEY-PTARMIGAN.jpeg
      2015-HADLEY-EAST-LAKE-REFLECTION.jpg
      2015-HADLEY-INDEX-BOULDERING.jpeg
      2015-HADLEY-INDEX-BOULDERING-2.jpeg
      2017-HADLEY-JTREE-HEADSTONE-2.jpg
      2016-HADLEY-DENALI.jpeg
      2016-HADLEY-RAINIER-EMMONS.jpg
      2018-HADLEY-POINCENOT-DESCENT-TORRES.jpg
      2015-HADLEY-MATT-FREE-SOLO.jpg
      2017-HADLEY-VINI-MIND-CONTROL.jpg
      2018-HADLEY-MERMOZ-RED-PILLAR.jpg
      2016-HADLEY-RAINIER-EMMONS-2.jpg
      2016-HADLEY-CARDS-IN-TENT.jpg
      2017-HADLEY-JOSHUA-TREE-SUNSET.jpg
      2017-HADLEY-JTREE-BOXERS-1.jpg
    ]
  end
end
